---
# Elasticsearch Ansible Playbook
- hosts: all
  user: ubuntu
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/agari.yml
    - vars/keys.yml

  tasks:
    - include: tasks/main.yml
    - include: tasks/aws.yml
